### ISSUE TITLE
Fix CR/LF issue with client generation from swagger.json

### ISSUE THREAD

**Issue by timvahlbrock** [Oeffis/Oeffis#160]
When generating client with swagger on a Windows machine, generated API files are showing up as changed in git while their content hasn´t changed at all. The only difference is line endings has changed from CR/LF (windows default) to LF. After each generation you have to pick out the files that really have changed (content-wise).

It should be looked into, if there's a fix, so that files with changed content are showing up only.

Additional steps to fix are documented in wiki: https://github.com/Oeffis/Oeffis/wiki/Best-Practices---Fixes

- [x] Introduce/implement fix
- [x] Document additional steps that may be necessary

**Comment by JaJako** [comment]
Time spent: 2 hours

Reproducing the issue together and trying some approaches of fixing the problem.

**Comment by JaJako** [comment]
@dkrakau I've commited what I have tested with the .gitattributes file. It actually does solve the problem with CRLF / LF as I found out later. Now the generated API files are checked out with LF line endings. So theoretically generation should not change the files anymore (because they are LF already). 
But at least on my side the files still show up: because of any reason the generation changes the last line ending of each generated file from LF to CRLF now (all other line endings of the files stay at LF).

**Comment by JaJako** [comment]
Time spent: 30 minutes

Further testing and adjustment + adding PR draft.

**Comment by JaJako** [comment]
A fix was found, that worked on two separate windows machines:
- generated API files are getting checked out with LF line endings (no conversion to CR/LF by git)
- after committing all files that have not changed content-wise once, they are not showing up again

**Comment by JaJako** [comment]
As it turns out the format of the checked out files (CRLF vs. LF) does not affect the issue or fixes it. It's enough to just stage (or try to commit) all files that have changed only line endings wise to eliminate the issue.

**Comment by JaJako** [comment]
Steps to eliminate problem:

1. Ensure all unstaged files have changed line endings only (no changes in content)
2. Stage all files (`git add .`) / try to commit the files
3. The files disappear, no commit has happened
4. Re-Run `npm run generate-client`, unchanged files should not appear again

**Comment by dkrakau** [comment]
Time spent: 2 hours 30 minutes
