### ISSUE TITLE
Create Client for VRR-API

### ISSUE THREAD

**Issue by Escowei98** [Oeffis/Oeffis#172]
```[tasklist]
### Tasks
```

**Comment by Paulomart** [comment]
Time spent: 30 minutes

I have used the schemas to generate all typescript classes. Sadly there are duplicates in the definition that need to be removed. Im looking into that later.

**Comment by Paulomart** [comment]
I think the solutions for the module problems are in this branch: https://github.com/Oeffis/Oeffis/pull/188

**Comment by timvahlbrock** [comment]
> I think the solutions for the module problems are in this branch: #188

yes probably. Feel free to review.

**Comment by timvahlbrock** [comment]
There have been esm issues, that prevented the backend from starting.

**Comment by timvahlbrock** [comment]
How far are you on this? I'm currently working on #189 and am currently implementing the faking of the server we get our data from. If you are mostly done with this, I won't bother mocking HAFAS and switching to VRR directly.

**Comment by Paulomart** [comment]
@timvahlbrock I would prefer if you would create an abstract mocking layer, so that both the HAFAS and VRR api can be used.

**Comment by timvahlbrock** [comment]
The problem is, that the end to end tests are running in containers, so introducing a separation layer would require adding an additional Webserver. Maybe a good idea in the long run, but a little much overhead at the current point?

**Comment by Paulomart** [comment]
@timvahlbrock I see now what you mean with this problem. Its not responable to mock away the vrr api. We should do it on the adapter level, between the app and the vrr api client. Maybe we can introduce a "switch" that enables mocked data for testing?

**Comment by timvahlbrock** [comment]
> @timvahlbrock I see now what you mean with this problem. Its not responable to mock away the vrr api. We should do it on the adapter level, between the app and the vrr api client. Maybe we can introduce a "switch" that enables mocked data for testing?

I think we shouldn't use static mock data, as this will strongly limit our testing abilities. Im not so keen on using a binary switch either. Maybe have the VRR Client be another nest app, which is started within the backend Container by default but the url can be overridden by env variable. The advantage of that would be, that we could define our own api spec for the interface. That could be used by the mock server, significantly reducing the effort required to mock a route (as the mocks server has built in support for this).

**Comment by timvahlbrock** [comment]
One of the main problems will be, that it won't be very easy or convenient to get a test mock into the running container used during e2e testing. So the most clean option would be to have either the backend or the VRR client query an HTTP API. The earlier would be nicer in terms of decoupling, but would introduce additional complexity, as then the VRR client would need to be accessible using HTTP too. The later would increase coupling between the backend and the VRR client. However, as it is not even clear, wether we even will be able to implement additional datasource clients due to the limited time in this project. Additionally, the interface between backend and datasources might change in later stages of the project. Therefore I would propose to - for now - accept the coupling between backend and VRR client and the backend, but somewhat reducing the time needed to implement and test this.

**Comment by timvahlbrock** [comment]
Time spent: 1 hour

Spent on:
- discussion
- drafting

**Comment by Paulomart** [comment]
Time spent: 10 hours

* Had many issues with github actions: Seems like a bug in github. See here: https://github.com/actions/setup-node/issues/215#issuecomment-1655193280
* Finished pr; discussed with @timvahlbrock

**Comment by timvahlbrock** [comment]
Time spent: 1 hours

Spent on:

- review
- discussion
