### ISSUE TITLE
Regression: Cannot remove Favorite Stops anymore

### ISSUE THREAD

**Issue by Paulomart** [Oeffis/Oeffis#359]
**Describe the bug**

You cannot remove favorite stops anymore.

**To Reproduce**

1. Add a new favorite stop when searching 
2. Try to remove it while still having the search input with the text
3. It wont work (it should)
4. Remove text from search input
5. Try again to remove, it wont work (it should)
6. Close modal
7. Try to remove again, it wont work (it should)

**Comment by Paulomart** [comment]
Seems to be caused by https://github.com/Oeffis/Oeffis/pull/342. Tested it before and after merging this. @timvahlbrock

**Comment by timvahlbrock** [comment]
Can you try clearing you localstorage?

**Comment by timvahlbrock** [comment]
@Paulomart created a PR to fix this. the problem was that there is an id of the location we get from the server, but also one that identifies a persisted item. Which means, now if you want to delete something, it's not enough to have the location, but you also have to find the location within the persisted locations to get the id to delete it. Maybe we could modify persistence to store atomic values instead, which we could compare directly? But not in this issue.

**Comment by timvahlbrock** [comment]
Time spent: 30 minutes

Spent on:
+ a6fe99034b4629290f96fd7e216c93d29626556f fix usage of wrong id to delete favorite stop
